export const FOLDERS = ["folders"]
export const FOLDERS_DELETED = ["folders_deleted"]
export const NOTES = ["notes"]
export const TASKS = ["tasks"]
export const TIME = ["time"]
export const USER = ["user"]
